[build]
  command = "npx prisma generate --schema=server/prisma/schema.prisma && npm run build -w client"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["node_modules/.prisma/**", "server/node_modules/.prisma/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
